name: "PR"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Build plugin
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apm-lyrics-ndp
          path: apm-lyrics-ndp.ndp
